#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("myCommunity.Droid.Resource", IsApplication=true)]

namespace myCommunity.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::myCommunity.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::myCommunity.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::myCommunity.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::myCommunity.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::myCommunity.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::myCommunity.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::myCommunity.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::myCommunity.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::myCommunity.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::myCommunity.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::myCommunity.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::myCommunity.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::myCommunity.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::myCommunity.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::myCommunity.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::myCommunity.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::myCommunity.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::myCommunity.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::myCommunity.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::myCommunity.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::myCommunity.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::myCommunity.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::myCommunity.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::myCommunity.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::myCommunity.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::myCommunity.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::myCommunity.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::myCommunity.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::myCommunity.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::myCommunity.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::myCommunity.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::myCommunity.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::myCommunity.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::myCommunity.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::myCommunity.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::myCommunity.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::myCommunity.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::GalaSoft.MvvmLight.Resource.String.ApplicationName = global::myCommunity.Droid.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Resource.String.Hello = global::myCommunity.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::myCommunity.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::myCommunity.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int custom_theme_color = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int calendar_drawer = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ernicommunity = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_refresh = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_description = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_errorstatus = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_event_date = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_launcher = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_location = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_news = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_participants = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_successstatus = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_time = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_type = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int monoandroidsplash = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int mycommunity_app_icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int nopizza = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int pizza = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int roundedbg = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int roundedbgdark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int splash_drawable = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int splashlogo = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int loadingImage = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int loadingProgressBar = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int loadingProgressWheel = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int textViewStatus = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int loading = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loadingimage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingprogress = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Mono_Android_Theme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
